---
services:
  pos:
    container_name: hebrews-pos
    build: .
    ports:
      - "8001:5000"
    volumes:
      - ./app/db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
    environment:
      - FLASK_SECRET_KEY
      - APP_USERNAME
      - APP_PASSWORD