---
services:
  pos:
    container_name: hebrews-pos
    image: hebrew-pos:1.7
    ports:
      - "5001:5000"
    volumes:
      - /opt/appdata/hebrews-pos/sqlite3/db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
