---
services:
  pos:
    container_name: hebrews-pos
    build: .
    ports:
      - "8001:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_SECRET_KEY
      - APP_USERNAME
      - APP_PASSWORD