---
services:
  pos:
    # build: .
    image: hebrew-pos:1.5
    ports:
      - "5000:5000"
    volumes:
      - /opt/appdata/hebrews-pos/sqlite3/db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
