---
services:
  pos:
    container_name: hebrews-pos
    image: hebrew-pos:1.8
    ports:
      - "5000:5000"
    volumes:
      - /opt/appdata/hebrews-pos/sqlite3/db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
    environment:
      - FLASK_SECRET_KEY
      - APP_USERNAME
      - APP_PASSWORD